name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@f5548c55522a1db0af3c84f2af3d058bc9bc2de2
        with:
          python-version: "3.13"
      - run: uv build
      - uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33
        with:
          verify-metadata: false
          password: ${{ secrets.PYPI_API_TOKEN }}
